# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: todolist
services:
- name: service
  project: src/resource-access/Service/Service.csproj
  bindings:
    - protocol: https
- name: webapi
  project: src/entrypoints/WebAPI/WebAPI.csproj
  bindings:
    - protocol: https
- name: web
  project: src/clients/Web/Web.csproj
  bindings:
    - protocol: https
      port: 8080
- name: otel
  image: amazon/aws-otel-collector:latest
  args: --config /config/collector-config-local.yml
  volumes:
    - source: ./data/otel
      target: /config
    - source: ./.awscredentials
      target: /root/.aws/credentials
  bindings:
    - protocol: http
      containerPort: 4317
  env:
    - name: AWS_REGION
      value: eu-north-1

# docker run --rm --attach STDOUT -v C:\Users\Renato\.aws\:/root/.aws:ro -e AWS_REGION=eu-north-1 -e AWS_PROFILE=todo --name xray-daemon -p 2000:2000/udp amazon/aws-xray-daemon -o